"""first migration

Revision ID: 75c1988ba566
Revises: 5e65c75cf165
Create Date: 2022-11-02 11:46:02.934883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c1988ba566'
down_revision = '5e65c75cf165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('ban_duration', sa.Integer(), nullable=True),
    sa.Column('ban_start', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_black_list_id'), 'black_list', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_black_list_id'), table_name='black_list')
    op.drop_table('black_list')
    # ### end Alembic commands ###
